name: Deploy Laravel to HostGator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write SSH key to file
        run: |
          echo "$DEPLOY_KEY" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
        env:
          DEPLOY_KEY: ${{ secrets.HOSTGATOR_SSH_KEY }}

      - name: Deploy via SCP (nativo)
        run: |
          scp -o KexAlgorithms=+diffie-hellman-group-exchange-sha256 \
              -o StrictHostKeyChecking=no \
              -i /tmp/deploy_key -P 22 -r . \
              peric572@162.241.203.155:/home1/peric572/public_html/amsilotti

      - name: Run SSH commands on HostGator
        run: |
          ssh -o KexAlgorithms=+diffie-hellman-group-exchange-sha256 \
              -o StrictHostKeyChecking=no \
              -i /tmp/deploy_key -p 22 peric572@162.241.203.155 '
            cd /home1/peric572/public_html/amsilotti &&
            composer install --no-interaction --prefer-dist --optimize-autoloader &&
            php artisan config:cache &&
            php artisan route:cache
            # php artisan migrate --force
          '
