name: Deploy Laravel to HostGator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HOSTGATOR_SSH_KEY }}

      - name: Copy project files to HostGator
        uses: appleboy/scp-action@master
        with:
          host: 162.241.203.155
          username: peric572
          key: ${{ secrets.HOSTGATOR_SSH_KEY }}
          port: 22
          source: "."
          target: "/home1/peric572/public_html/amsilotti"
          rm: true
          strip_components: 0
          args: "-oKexAlgorithms=+diffie-hellman-group-exchange-sha256"

      - name: Run SSH commands on HostGator
        uses: appleboy/ssh-action@master
        with:
          host: 162.241.203.155
          username: peric572
          key: ${{ secrets.HOSTGATOR_SSH_KEY }}
          port: 22
          args: "-oKexAlgorithms=+diffie-hellman-group-exchange-sha256"
          script: |
            cd /home1/peric572/public_html/amsilotti
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan config:cache
            php artisan route:cache
            # php artisan migrate --force
